{% set version = "0.21.5.25" %}

package:
  name: trash-cli
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/trash-cli/trash-cli-{{ version }}.tar.gz
  sha256: c58905b04a60bb70231648ac6f280965a4cfdd2e2682e6d94b12f99a40620538

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - psutil

test:
  imports:
    - trashcli
  commands:
    - pip check
    - trash -h
    - trash-put -h
    - trash-list -h
    - trash-restore -h
    - trash-empty -h
    - trash-rm -h
  requires:
    - pip

about:
  home: https://github.com/andreafrancia/trash-cli
  license: GPL-2.0-or-later
  license_file: COPYING
  summary: Command line interface to FreeDesktop.org Trash.

extra:
  recipe-maintainers:
    - ocefpaf
