{% set version = "0.22.8.19" %}

package:
  name: trash-cli
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/trash-cli/trash-cli-{{ version }}.tar.gz
  sha256: f1e92eac01bff0bf878ce62e9689589bc6d856b58959f8f0c74ce9787f049f5f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - psutil

test:
  imports:
    - trashcli
  commands:
    - pip check
    - trash -h
    - trash-put -h
    - trash-list -h
    - trash-restore -h
    - trash-empty -h
    - trash-rm -h
  requires:
    - pip

about:
  home: https://github.com/andreafrancia/trash-cli
  license: GPL-2.0-or-later
  license_file: COPYING
  summary: Command line interface to FreeDesktop.org Trash.

extra:
  recipe-maintainers:
    - ocefpaf
