{% set version = "0.23.9.23" %}

package:
  name: trash-cli
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/trash-cli/trash-cli-{{ version }}.tar.gz
  sha256: d367f0a70b3b1c20d97bcb459c552eeefc42e7e8d00f2af334236708ec047584

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - psutil
    - six
    # optional fot autocomplete
    - shtab
    - typing

test:
  imports:
    - trashcli
  commands:
    #- pip check
    - trash -h
    - trash-put -h
    - trash-list -h
    - trash-restore -h
    - trash-empty -h
    - trash-rm -h
  requires:
    - pip

about:
  home: https://github.com/andreafrancia/trash-cli
  license: GPL-2.0-or-later
  license_file: COPYING
  summary: Command line interface to FreeDesktop.org Trash.

extra:
  recipe-maintainers:
    - ocefpaf
