{% set version = "0.22.10.20" %}

package:
  name: trash-cli
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/trash-cli/trash-cli-{{ version }}.tar.gz
  sha256: 14e0a95cd6d3943ef682530568d7894366c1733eb07723e693c5410a3c74fe0f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - psutil
    - six
    # optional fot autocomplete
    - shtab

test:
  imports:
    - trashcli
  commands:
    - pip check
    - trash -h
    - trash-put -h
    - trash-list -h
    - trash-restore -h
    - trash-empty -h
    - trash-rm -h
  requires:
    - pip

about:
  home: https://github.com/andreafrancia/trash-cli
  license: GPL-2.0-or-later
  license_file: COPYING
  summary: Command line interface to FreeDesktop.org Trash.

extra:
  recipe-maintainers:
    - ocefpaf
