schema_version: 1

context:
  version: 0.26.9.29

package:
  name: trash-cli
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/t/trash-cli/trash_cli-${{ version }}.tar.gz
  sha256: 2ca3300fd9f3b0334cb3f576a3ec95ced8593cc729df4332608d69a28eb50fb0

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools
    - pip
  run:
    - python >=${{ python_min }}
    - psutil
    - six
    - typing_extensions <4.14.0
    - enum34
    - typing
tests:
  - python:
      imports:
        - trashcli
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - '*'
    script:
      - trash -h
      - trash-put -h
      - trash-list -h
      - trash-restore -h
      - trash-empty -h
      - trash-rm -h

about:
  summary: Command line interface to FreeDesktop.org Trash.
  license: GPL-2.0-only
  license_file: COPYING
  homepage: https://github.com/andreafrancia/trash-cli

extra:
  recipe-maintainers:
    - ocefpaf
